"""Static remediation guidance, keyed by finding id with a category fallback.

Reports are read by people who then have to go fix the thing; a bare
"cookie-not-httponly" id tells a report reader what fired, not what to do
about it. This is data, not scanning logic, so it carries zero risk to the
Python/Go parity contract that report-generator's callers depend on.
"""

from __future__ import annotations

# Exact finding-id guidance. Checked first; falls back to _CATEGORY below.
_BY_ID: dict[str, str] = {
    "insecure-cookie": "Set the Secure flag on this cookie so it is never sent over plain HTTP.",
    "cookie-not-httponly": "Set HttpOnly on this cookie so client-side JS (and XSS) cannot read it.",
    "cookie-samesite-none-without-secure": "SameSite=None cookies must also carry Secure; add it or use SameSite=Lax/Strict.",
    "cookie-domain-broad": "Scope the cookie's Domain to the exact host that needs it instead of a parent domain.",
    "cookie-secure-prefix-violation": "Add the Secure flag (required by the __Secure- prefix) or drop the prefix -- as-is, browsers silently reject this Set-Cookie entirely.",
    "cookie-host-prefix-violation": "Fix the flagged attribute(s) to meet the __Host- prefix's requirements (Secure, no Domain, Path=/) or drop the prefix -- as-is, browsers silently reject this Set-Cookie entirely.",
    "cookie-path-broad": "Scope session cookies to the narrowest Path that still works, not '/'.",
    "missing-csp": "Add a Content-Security-Policy header restricting script/style/object sources.",
    "weak-csp": "Tighten the CSP: drop 'unsafe-inline'/'unsafe-eval' and wildcard sources in favor of nonces/hashes.",
    "csp-wildcard-script": "Replace the wildcard script-src with an explicit allowlist, nonce, or hash.",
    "csp-missing-frame-ancestors": "Add frame-ancestors to the CSP (or X-Frame-Options) to prevent clickjacking.",
    "csp-report-only": "Content-Security-Policy-Report-Only does not block anything; enforce it once tuned.",
    "missing-x-frame-options": "Add X-Frame-Options: DENY/SAMEORIGIN or a CSP frame-ancestors directive.",
    "missing-hsts": "Add Strict-Transport-Security so browsers never downgrade this origin to plain HTTP.",
    "short-hsts": "Raise the HSTS max-age (a year is standard) and consider includeSubDomains/preload.",
    "missing-x-content-type-options": "Add X-Content-Type-Options: nosniff to stop MIME-sniffing attacks.",
    "weak-x-content-type-options": "Set X-Content-Type-Options to exactly 'nosniff'.",
    "missing-referrer-policy": "Add a Referrer-Policy header (e.g. strict-origin-when-cross-origin) to limit leakage.",
    "server-version-leak": "Suppress the Server/X-Powered-By version string; it hands attackers a CVE shortlist.",
    "x-powered-by": "Remove or genericize the X-Powered-By header.",
    "cors-wildcard-credentials": "Never combine Access-Control-Allow-Origin: * with Allow-Credentials: true; echo a specific allowlisted origin instead.",
    "cors-allow-any": "Validate Access-Control-Allow-Origin against an explicit allowlist instead of a wildcard.",
    "cors-reflect-origin": "Validate Access-Control-Allow-Origin against an explicit allowlist instead of blindly reflecting the request's Origin header.",
    "jwt-alg-none": "Reject tokens with alg: none server-side; never trust the algorithm a client supplies.",
    "jwt-weak-secret": "Rotate to a long, random HMAC secret (32+ bytes) generated by a CSPRNG.",
    "jwt-missing-exp": "Always set and enforce an exp claim so stolen tokens expire.",
    "jwt-long-expiry": "Shorten token lifetime and use refresh tokens instead of long-lived access tokens.",
    "html-comment": "Strip debug/TODO/credential comments from HTML shipped to production.",
    "meta-generator": "Remove or genericize the generator meta tag to reduce fingerprinting.",
    "mixed-content": "Serve this subresource over HTTPS; browsers may block or warn on the HTTP load.",
    "sri-missing": "Add a Subresource Integrity (integrity=\"sha384-...\") attribute to this cross-origin script/stylesheet.",
    "payload-command-injection": "Never build shell commands from user input. Use an exec-with-argument-array API (no shell=True/os.system/backticks) and, if a shell is unavoidable, allowlist and strictly validate the value first.",
    "payload-command-injection-blind": "Same fix as payload-command-injection: this was only confirmed via response timing, so treat it as a strong lead to verify manually, not a certainty.",
    "payload-crlf-header-injection": "Never build HTTP response headers by string-concatenating user input. Use your framework's header-setting API, which rejects embedded CR/LF, instead of writing raw header text.",
    "payload-crlf-reflected": "Encode or reject control characters (CR/LF) in this input before it reaches any response header or log line.",
    "payload-lfi": "Never pass user input into include()/require()/fopen(); use a fixed allowlist of file identifiers instead of a raw path/wrapper URI.",
    "payload-lfi-rce": "Disable allow_url_include and never pass user input into include()/require(); this is full remote code execution, treat as a critical incident.",
    "tls-cert-expired": "Renew this certificate immediately; browsers and API clients will refuse the connection.",
    "tls-cert-expiring-soon": "Renew this certificate before it expires; automate renewal (e.g. ACME/Let's Encrypt) to avoid this recurring.",
    "tls-cert-self-signed": "Replace with a certificate from a trusted CA; a self-signed cert can't be verified by normal clients without manual trust.",
    "tls-hostname-mismatch": "Issue a certificate that actually covers this hostname (correct SAN entries), or fix the DNS/routing sending traffic here.",
    "tls-untrusted-chain": "Issue a certificate from a CA in standard trust stores, and ensure the server sends its full intermediate chain.",
    "tls-handshake-failed": "Investigate the TLS handshake failure -- often an obsolete protocol/cipher configuration a modern client refuses to negotiate.",
    "waf-challenge": "Informational: a WAF/bot-mitigation challenge was detected, not a vulnerability by itself.",
    "waf-challenge-sitewide": "Allowlist the scanner's IP/UA with the WAF operator; most of this scan was blocked, not clean.",
    "verbose-error": "Turn off debug/verbose error pages in production; log stack traces server-side only.",
    "autocomplete": "Add autocomplete=\"off\"/\"new-password\" to sensitive fields, or accept the browser tradeoff deliberately.",
    "missing-rate-limit": "Add rate limiting/lockout on this auth endpoint to slow down credential stuffing.",
    "session-fixation": "Issue a new session identifier on login instead of reusing the pre-auth session.",
    "logout-session-not-invalidated": "Invalidate the session server-side on logout, not just by clearing the client cookie.",
    "authz-still-accessible": "This URL returned success for a lower-privileged session that replayed a higher-privileged crawl; verify whether that access is intentional, and enforce authorization checks server-side per-object, not just per-route.",
    "authz-broken-access-control": "This URL enforces *some* session but not the *right* one -- a lower-privileged session can reach it while an anonymous request is denied. Enforce authorization checks server-side per-object, not just per-route.",
    "idor-adjacent-id-accessible": "First confirm the adjacent ID actually belongs to a different account (not just another of your own records); if so, enforce an object-level authorization check on this endpoint instead of trusting that any valid session may access any ID.",
    "oauth-missing-state": "Add a random, unguessable state parameter to the authorization request and verify it matches on the callback, to prevent CSRF against the OAuth flow.",
    "reset-token-sequential": "Generate reset/verification tokens with a CSPRNG (e.g. 32+ random bytes), never a sequential, incrementing, or timestamp-derived value.",
    "reset-token-small-keyspace": "Lengthen the reset/verification token and/or widen its alphabet, and add real rate limiting/lockout on repeated attempts against this endpoint.",
    "reset-token-short": "Lengthen the reset/verification token (aim for 128+ bits of real entropy) and confirm it's generated with a CSPRNG.",
    "reset-token-in-url": "Deliver the token via a one-time POST body or a single-use, immediately-consumed redirect instead of a persistent URL, to avoid Referer/log/history leakage.",
    "oauth-implicit-flow": "Migrate off the implicit flow (response_type=token) to the authorization code flow with PKCE; the implicit flow exposes the access token in the URL fragment.",
    "auth-stack-next-auth": "Informational fingerprint: next-auth is in use. Review callbackUrl handling and cookie prefix contracts for this stack.",
    "next-auth-callback-url-unvalidated": "Allowlist callbackUrl against the app's own origin (next-auth AUTH_URL / AUTH_ALLOWED_CALLBACKS) so an attacker-controlled URL cannot land in the callback-url cookie or post-login redirect.",
    "auth-stack-keycloak": "Informational fingerprint: Keycloak is in use. Review redirect_uri allowlists and token-endpoint auth separately.",
    "auth-stack-auth0": "Informational fingerprint: Auth0 is in use. Review allowed callback URLs in the Auth0 application settings.",
}

# Category fallback for ids not listed above (new payload/secret pack ids
# especially — those are added far more often than this table is updated).
_BY_CATEGORY: dict[str, str] = {
    "cookie": "Review the cookie's Secure/HttpOnly/SameSite/Domain/Path attributes.",
    "header": "Review the response header for a safer, more restrictive value.",
    "secret": "Rotate the exposed credential immediately and remove it from the response/source.",
    "exposed-file": "Remove or restrict access to this file; it should not be reachable by unauthenticated requests.",
    "auth": "Review authentication/session handling for this endpoint.",
    "payload": "Validate and encode this input server-side; never trust client-supplied values in queries, commands, templates, or paths.",
    "waf-challenge": "Informational: a bot-mitigation challenge was detected, not a vulnerability by itself.",
    "tls": "Review this host's TLS certificate configuration (validity, issuer, hostname coverage).",
    "verbose-error": "Disable verbose/debug error output in production.",
    "js-endpoint": "Informational: an API endpoint was discovered in client-side JS; confirm it enforces its own authz.",
    "scan-note": "Informational: an active probe was intentionally skipped for this URL, not a vulnerability by itself -- other checks against it were not meaningfully performed either.",
}

_DEFAULT = "Review this finding's evidence and confirm whether it is exploitable in this deployment."


def remediation_for(finding_id: str, category: str = "") -> str:
    if finding_id in _BY_ID:
        return _BY_ID[finding_id]
    if category in _BY_CATEGORY:
        return _BY_CATEGORY[category]
    return _DEFAULT
