"""Static remediation guidance, keyed by finding id with a category fallback.

Reports are read by people who then have to go fix the thing; a bare
"cookie-not-httponly" id tells a report reader what fired, not what to do
about it. This is data, not scanning logic, so it carries zero risk to the
Python/Go parity contract that report-generator's callers depend on.
"""

from __future__ import annotations

# Exact finding-id guidance. Checked first; falls back to _CATEGORY below.
_BY_ID: dict[str, str] = {
    "insecure-cookie": "Set the Secure flag on this cookie so it is never sent over plain HTTP.",
    "cookie-not-httponly": "Set HttpOnly on this cookie so client-side JS (and XSS) cannot read it.",
    "cookie-samesite-none-without-secure": "SameSite=None cookies must also carry Secure; add it or use SameSite=Lax/Strict.",
    "cookie-domain-broad": "Scope the cookie's Domain to the exact host that needs it instead of a parent domain.",
    "cookie-path-broad": "Scope session cookies to the narrowest Path that still works, not '/'.",
    "missing-csp": "Add a Content-Security-Policy header restricting script/style/object sources.",
    "weak-csp": "Tighten the CSP: drop 'unsafe-inline'/'unsafe-eval' and wildcard sources in favor of nonces/hashes.",
    "csp-wildcard-script": "Replace the wildcard script-src with an explicit allowlist, nonce, or hash.",
    "csp-missing-frame-ancestors": "Add frame-ancestors to the CSP (or X-Frame-Options) to prevent clickjacking.",
    "csp-report-only": "Content-Security-Policy-Report-Only does not block anything; enforce it once tuned.",
    "missing-x-frame-options": "Add X-Frame-Options: DENY/SAMEORIGIN or a CSP frame-ancestors directive.",
    "missing-hsts": "Add Strict-Transport-Security so browsers never downgrade this origin to plain HTTP.",
    "short-hsts": "Raise the HSTS max-age (a year is standard) and consider includeSubDomains/preload.",
    "missing-x-content-type-options": "Add X-Content-Type-Options: nosniff to stop MIME-sniffing attacks.",
    "weak-x-content-type-options": "Set X-Content-Type-Options to exactly 'nosniff'.",
    "missing-referrer-policy": "Add a Referrer-Policy header (e.g. strict-origin-when-cross-origin) to limit leakage.",
    "server-version-leak": "Suppress the Server/X-Powered-By version string; it hands attackers a CVE shortlist.",
    "x-powered-by": "Remove or genericize the X-Powered-By header.",
    "cors-wildcard-credentials": "Never combine Access-Control-Allow-Origin: * with Allow-Credentials: true; echo a specific allowlisted origin instead.",
    "cors-misconfig": "Validate Access-Control-Allow-Origin against an explicit allowlist, not request-reflected or wildcard.",
    "graphql-introspection": "Disable introspection in production, or gate it behind authentication.",
    "jwt-alg-none": "Reject tokens with alg: none server-side; never trust the algorithm a client supplies.",
    "jwt-weak-secret": "Rotate to a long, random HMAC secret (32+ bytes) generated by a CSPRNG.",
    "jwt-missing-exp": "Always set and enforce an exp claim so stolen tokens expire.",
    "jwt-long-expiry": "Shorten token lifetime and use refresh tokens instead of long-lived access tokens.",
    "jwt-alg-confusion-possible": "Pin the expected algorithm server-side (don't trust the header) so an RS256 public key can't be replayed as an HS256 secret.",
    "html-comment": "Strip debug/TODO/credential comments from HTML shipped to production.",
    "meta-generator": "Remove or genericize the generator meta tag to reduce fingerprinting.",
    "mixed-content": "Serve this subresource over HTTPS; browsers may block or warn on the HTTP load.",
    "sri-missing": "Add a Subresource Integrity (integrity=\"sha384-...\") attribute to this cross-origin script/stylesheet.",
    "outdated-js-library": "Upgrade this library past the version with known CVEs (see evidence for the detected version).",
    "waf-challenge": "Informational: a WAF/bot-mitigation challenge was detected, not a vulnerability by itself.",
    "waf-challenge-sitewide": "Allowlist the scanner's IP/UA with the WAF operator; most of this scan was blocked, not clean.",
    "verbose-error": "Turn off debug/verbose error pages in production; log stack traces server-side only.",
    "autocomplete-password": "Add autocomplete=\"off\"/\"new-password\" to sensitive fields, or accept the browser tradeoff deliberately.",
    "rate-limit-missing": "Add rate limiting/lockout on this auth endpoint to slow down credential stuffing.",
    "session-fixation": "Issue a new session identifier on login instead of reusing the pre-auth session.",
    "logout-not-invalidated": "Invalidate the session server-side on logout, not just by clearing the client cookie.",
    "authz-diff": "This URL returned success for a lower-privileged session that replayed a higher-privileged crawl; enforce authorization checks server-side per-object, not just per-route.",
}

# Category fallback for ids not listed above (new payload/secret pack ids
# especially — those are added far more often than this table is updated).
_BY_CATEGORY: dict[str, str] = {
    "cookie": "Review the cookie's Secure/HttpOnly/SameSite/Domain/Path attributes.",
    "header": "Review the response header for a safer, more restrictive value.",
    "secret": "Rotate the exposed credential immediately and remove it from the response/source.",
    "exposed-file": "Remove or restrict access to this file; it should not be reachable by unauthenticated requests.",
    "auth": "Review authentication/session handling for this endpoint.",
    "payload": "Validate and encode this input server-side; never trust client-supplied values in queries, commands, templates, or paths.",
    "waf-challenge": "Informational: a bot-mitigation challenge was detected, not a vulnerability by itself.",
    "verbose-error": "Disable verbose/debug error output in production.",
    "js-endpoint": "Informational: an API endpoint was discovered in client-side JS; confirm it enforces its own authz.",
}

_DEFAULT = "Review this finding's evidence and confirm whether it is exploitable in this deployment."


def remediation_for(finding_id: str, category: str = "") -> str:
    if finding_id in _BY_ID:
        return _BY_ID[finding_id]
    if category in _BY_CATEGORY:
        return _BY_CATEGORY[category]
    return _DEFAULT
